### ISSUE TITLE
Exception has occurred: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by novenix** [czetsuya/keycloak-rest-admin-api#1]
hi im running the application, i have a keycloak 9.0.3 docker image running, and when i run in local not works, if i try to get roles, and debug says this error.
its happening in a JWSInput.class in line 45:
if (parts.length < 2 || parts.length > 3) throw new IllegalArgumentException("Parsing error");
Error: "Exception has occurred: java.lang.IllegalArgumentException
"java.lang.IllegalArgumentException: Parsing error"" 
pls help thanks

**Comment by czetsuya** [comment]
Hi Novenix,

I tried locally in the said version and it's working. Here's what I did.

1.) Created the realm using the one inside the config folder (you can import it balambgarden-realm.json).
2.) Imported the users from the config/balambgarden-users-0.json file. 
3.) Import this project in Postman keycloak-admin-api.postman_collection.json.
4.) Make sure that the login request is pointing to where you are running Keycloak. If it is in docker then just expose the port correctly.
5.) Start from the login request and the other 2 requests should work.
